import type { Metadata } from 'next'
import './globals.css'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'



export const metadata: Metadata = {
  title: 'Travel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body>
      <Navbar />
      <main className="relative overflow-hiden">{children}</main>
     
      <Footer />
      </body>
    </html>
  )
}
